name: Generate vimdoc

on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/panvimdoc.yml

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: README to vimdoc
    steps:
      - uses: actions/checkout@v2

      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "NVIM v0.10.0"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate vimdoc using panvimdoc"
          branch: ${{ github.head_ref }}
